
name: Haraka CI

on:
  push:
  workflow_call:

env:
  CI: true
  node-version: 16

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/lint

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/coverage

  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/codeql
