name: CI

on:
  push:
  pull_request:

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  coverage:
    uses: haraka/.github/.github/workflows/coverage.yml@master
    secrets: inherit

  ubuntu:
    needs: [lint]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    needs: [lint]
    uses: haraka/.github/.github/workflows/windows.yml@master

  # ubuntu:
  #   needs: [ lint, get-lts ]
  #   runs-on: ubuntu-latest
  #   services:
  #     redis:
  #       image: redis
  #       ports:
  #         - 6379:6379
  #   strategy:
  #     matrix:
  #       node-version: ${{ fromJson(needs.get-lts.outputs.lts) }}
  #     fail-fast: false
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     name: Node ${{ matrix.node-version }} on ubuntu-latest
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm install
  #   - run: npm test

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      lts: ${{ steps.get.outputs.lts }}
      min: ${{ steps.get.outputs.min }}
