
name: Haraka Project CI

on:
  push:
  workflow_call:

env:
  CI: true
  node-version: 16

jobs:

  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      name: Node ${{ env.node-version }}
      with:
        node-version: ${{ env.node-version }}

  lint:
    runs-on: ubuntu-latest
    needs: node
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    needs: node
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - run: npm install
    - name: run coverage
      run: |
        npm install --no-save nyc codecov
        npx nyc --reporter=lcov npm test

    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: false

    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
