name: publish

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  publish:
    # if needed, 'publish-redis.yml' is also available
    uses: haraka/.github/.github/workflows/publish.yml@master
    secrets: inherit
