name: publish

on:
  push:
    branches:
      - master
    paths:
      - package.json

permissions:
  id-token: write # required for OIDC
  contents: read

env:
  CI: true

jobs:
  publish:
    uses: haraka/.github/.github/workflows/publish.yml@master
    secrets: inherit
