name: Test Coverage

on:
  workflow_call:

env:
  CI: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/-1

    - uses: actions/checkout@v3
    - run: npm install
    - name: run coverage
      run: |
        npm install --no-save c8
        npx c8 --reporter=lcov npm test
      env:
        NODE_ENV: cov

    - name: codecov
      uses: codecov/codecov-action@v2

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
