name: Haraka CI

on:
  workflow_call:

env:
  CI: true

jobs:

  lint:
    uses: ./.github/workflows/lint

  coverage:
    uses: ./.github/workflows/coverage

  codeql:
    uses: ./.github/workflows/codeql

  publish:
    uses: ./.github/workflows/publish