
name: Lint

on:
  workflow_call:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint