
name: Lint

on:
  workflow_call:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run lint
