name: Lint

on:
  workflow_call:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npm ci || npm install
      - run: npm run lint
