name: Prettier

on:
  workflow_call:

env:
  CI: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npx prettier . --check
