name: Prettier

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

env:
  CI: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - uses: actions/setup-node@v6
      - run: npx prettier . --write
      - run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add -A
            git commit -m "style: format code with prettier" || echo "No changes to commit"
            git push
          else
            echo "No formatting changes"
          fi