name: Prettier

on:
  workflow_call:

env:
  CI: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - run: git checkout "${{ github.ref_name }}" || git checkout -b "${{ github.ref_name }}"
      - uses: actions/setup-node@v6
      - run: npx prettier . --write
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "style: format code with prettier" || echo "No changes to commit"
          git push