name: publish

on:
  workflow_call:

env:
  CI: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v6
      - run: npm ci || npm install
      - run: npm publish --provenance

  publish-ghpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@haraka'
      - name: rename package with @haraka scope
        run: node .release/js/prepend-scope.cjs @haraka
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
