name: CI

on:
  workflow_call:

env:
  CI: true

jobs:
  ubuntu:
    needs: [ get-lts ]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: Node ${{ matrix.node-version }} on ubuntu-latest
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      lts: ${{ steps.get.outputs.lts }}
