name: CI

on:
  workflow_call:

env:
  CI: true
  os: ubuntu-latest

jobs:
  ubuntu:
    needs: [ get-lts ]
    runs-on: ${{ env.os }}
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Node ${{ matrix.node-version }} on ${{ env.os }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test

  get-lts:
    runs-on: ${{ env.os }}
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      lts: ${{ steps.get.outputs.lts }}
