name: CI

on:
  workflow_call:

env:
  CI: true

jobs:
  ubuntu:
    needs: [get-lts]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.lts) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Node ${{ matrix.node-version }} on ubuntu-latest
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  ubuntu-node-current:
    needs: [get-lts]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      env:
        NODE_PENDING_DEPRECATION: 1
        NODE_OPTIONS: --pending-deprecation --throw-deprecation --trace-warnings --trace-deprecation
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Node ${{ matrix.node-version }} on ubuntu-latest
        with:
          node-version: ${{ fromJson(needs.get-lts.outputs.current) }}
      - run: npm install
      - run: npm test

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      current: ${{ steps.get.outputs.current }}
      lts: ${{ steps.get.outputs.lts }}

