name: CI

on:
  workflow_call:

env:
  CI: true

jobs:
  latest:
    needs: [get-lts]
    strategy:
      matrix:
        os: [windows-latest]
        node-version: ${{ fromJson(needs.get-lts.outputs.maintenance) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Node.js ${{ matrix.node-version }} on windows-latest
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      maintenance: ${{ steps.get.outputs.maintenance }}
      lts: ${{ steps.get.outputs.lts }}
      current: ${{ steps.get.outputs.current }}
      min: ${{ steps.get.outputs.min }}
