name: CI

on:
  workflow_call:

env:
  CI: true

jobs:
  latest:
    needs: [ get-lts ]

    # no docker/images support on Windows (currently), so run w/o Redis
    # also, stack run commands so test doesn't begin before install completes
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: Node.js ${{ matrix.node-version }} on windows-latest
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test

  w2019:
    needs: [ latest, get-lts ]
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: Node.js ${{ matrix.node-version }} on windows-2019
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      lts: ${{ steps.get.outputs.lts }}
